# Generated by Django 4.0.6 on 2022-07-26 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pqrs_person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(max_length=30)),
                ('identification_number', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('num_cell', models.IntegerField(blank=True, null=True)),
                ('num_house', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Pqrs_tiket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_title', models.CharField(max_length=30)),
                ('ticket_type', models.CharField(max_length=30)),
                ('ticket_content', models.CharField(max_length=250)),
                ('state', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda_PQRS_app.pqrs_person')),
            ],
        ),
    ]
