# Generated by Django 4.0.6 on 2022-07-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_PQRS_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pqrs_person',
            options={'ordering': ['id'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='pqrs_tiket',
            options={'ordering': ['id'], 'verbose_name': 'tiket', 'verbose_name_plural': 'tikets'},
        ),
        migrations.AlterField(
            model_name='pqrs_person',
            name='identification_number',
            field=models.IntegerField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='pqrs_person',
            name='type_document',
            field=models.CharField(choices=[('CC', 'cedula de ciudadania'), ('TI', 'tarjeta de identidad'), ('CE', 'cedula de extranjeria')], default='CC', max_length=30),
        ),
        migrations.AlterField(
            model_name='pqrs_tiket',
            name='ticket_content',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterModelTable(
            name='pqrs_person',
            table='users',
        ),
        migrations.AlterModelTable(
            name='pqrs_tiket',
            table='tikes',
        ),
    ]
