# Generated by Django 4.0.6 on 2022-07-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_PQRS_app', '0003_alter_pqrs_person_identification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrs_person',
            name='num_cell',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pqrs_person',
            name='num_house',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
