# Generated by Django 4.0.6 on 2022-07-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_PQRS_app', '0004_alter_pqrs_person_num_cell_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrs_person',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pqrs_tiket',
            name='ticket_type',
            field=models.CharField(choices=[('P', 'pregunta'), ('Q', 'queja'), ('R', 'reclamo'), ('S', 'sugerencias')], default='p', max_length=30),
        ),
    ]
