# Generated by Django 4.0.6 on 2022-07-26 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_PQRS_app', '0005_alter_pqrs_person_email_alter_pqrs_tiket_ticket_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pqrs_tiket',
            table='tikets',
        ),
    ]
