# Generated by Django 4.0.6 on 2022-07-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_PQRS_app', '0006_alter_pqrs_tiket_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pqrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('CC', 'cedula de ciudadania'), ('TI', 'tarjeta de identidad'), ('CE', 'cedula de extranjeria')], default='CC', max_length=30)),
                ('identification_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('num_cell', models.PositiveBigIntegerField(blank=True, null=True)),
                ('num_house', models.PositiveBigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=50)),
                ('ticket_title', models.CharField(max_length=30)),
                ('ticket_type', models.CharField(choices=[('P', 'pregunta'), ('Q', 'queja'), ('R', 'reclamo'), ('S', 'sugerencias')], default='P', max_length=30)),
                ('ticket_content', models.TextField(max_length=250)),
                ('state', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'pqrs',
                'verbose_name_plural': 'pqrss',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='pqrs_tiket',
            name='author',
        ),
        migrations.DeleteModel(
            name='Pqrs_person',
        ),
        migrations.DeleteModel(
            name='Pqrs_tiket',
        ),
    ]
