# Generated by Django 4.0.6 on 2022-07-27 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda_PQRS_app', '0007_pqrs_remove_pqrs_tiket_author_delete_pqrs_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqrs',
            name='identification_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='num_cell',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='num_house',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
